home:
    path: /
    methods: [GET]
    controller: App\Controller\Homepage::devHomepageAction
    
my_recipes:
    path: /my_recipes
    methods: [GET]
    controller: App\Controller\MyRecipes

add_recipe:
    path: /add_recipe
    methods: [GET, POST]
    controller: App\Controller\AddRecipe